image:
  width: 1080
  height: 1300
  background_color: '#000000'
  artwork:
    padding: 100
    vertical_offset: -20
    overlay:
      color:
      - 0
      - 0
      - 0
      opacity: 128
qr_code:
  spotify:
    base_url: https://scannables.scdn.co/uri/plain/png
    foreground: '#ffffff'
    background: black
    size: 300
    vertical_offset: 120
    invert_colors: false
text:
  title:
    font:
      name: Game Of Squids.ttf
      size: 100
    vertical_offset: -100
    alignment: center
    shadow:
      enabled: true
      offset: 3
      color: '#333333'
    color: '#ffffff'
  info:
    font:
      name: federalescort.ttf
      size: 45
    alignment: center
    color: '#ffffff'
  link:
    font:
      name: federalescort.ttf
      size: 30
    alignment: center
    color: '#cccccc'
  streaming:
    text: 'NOW STREAMING

      https://caelumwraith.com'
    vertical_offset: 80
    alignment: right
